site_name: DeepLearning
pages:
- "Home": 'index.md'
- "Get Started": 'get_started.md'
- "Deep Networks":
  - "Introduction": 'introduction.md'
  - "Recurent Neural Network": 'rnn.md'
  - "Convolutional Neural Network": 'cnn.md'
theme_dir: magizbox
markdown_extensions:
    - footnotes
    - mdx_math

extra_css:
  - components/magiz-c-book/src/book.css
  - components/magiz-c-course/src/course.css
  - components/magiz-c-video/src/video.css
  - components/magiz-c-benchmark/src/benchmark.css
  - components/magiz-c-paper/src/paper.css
  - components/magiz-doc/style.css
  - components/magiz-doc/highlight.css

extra_javascript:
  - components/underscore/underscore.js
  - components/magiz-c-book/src/gspreadsheet.js
  - components/magiz-c-paper/src/paper.js
  - components/magiz-c-course/src/course.js
  - components/magiz-c-benchmark/src/benchmark.js
  - components/magiz-c-benchmark/src/bootstrap-popup.js
  - components/magiz-c-book/src/book.js
  - components/magiz-c-video/src/video.js
  - components/magiz-doc/doc.js
  - components/magiz-doc/footer.js
