site_name: DeepLearning
pages:
- "Home": 'index.md'
- "Getting Started": 'getting_started.md'
- "Docs":
  - "Introduction": 'introduction.md'
  - "Recurent Neural Network": 'rnn.md'
  - "Convolutional Neural Network": 'cnn.md'
- "<span class='fa fa-rss'></span> News": "feed.md"

extra_css:
  - components/magiz-c-book/src/book.css
  - components/magiz-c-course/src/course.css
  - components/magiz-c-video/src/video.css
  - components/magiz-c-benchmark/src/benchmark.css
  - components/magiz-c-paper/src/paper.css
  - components/magiz-c-feed/src/feed.css

extra_javascript:
  - components/underscore/underscore.js
  - components/magiz-c-book/src/gspreadsheet.js
  - components/magiz-c-paper/src/paper.js
  - components/magiz-c-course/src/course.js
  - components/magiz-c-benchmark/src/benchmark.js
  - components/magiz-c-benchmark/src/bootstrap-popup.js
  - components/magiz-c-book/src/book.js
  - components/magiz-c-video/src/video.js
  - components/magiz-c-feed/src/feed.js
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math
  - footnotes
